apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xx1k9upzj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xx1k9upzj-go 
  name: xx1k9upzj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xx1k9upzj-go 
